# this code is auto generated by tools/prefix_tdx.py

from polars_ta.tdx.arithmetic import ABS  # noqa
from polars_ta.tdx.arithmetic import ACOS  # noqa
from polars_ta.tdx.arithmetic import ADD  # noqa
from polars_ta.tdx.arithmetic import ASIN  # noqa
from polars_ta.tdx.arithmetic import ATAN  # noqa
from polars_ta.tdx.arithmetic import BETWEEN  # noqa
from polars_ta.tdx.arithmetic import CEILING  # noqa
from polars_ta.tdx.arithmetic import COS  # noqa
from polars_ta.tdx.arithmetic import EXP  # noqa
from polars_ta.tdx.arithmetic import FLOOR  # noqa
from polars_ta.tdx.arithmetic import FRACPART  # noqa
from polars_ta.tdx.arithmetic import LN  # noqa
from polars_ta.tdx.arithmetic import LOG  # noqa
from polars_ta.tdx.arithmetic import MAX  # noqa
from polars_ta.tdx.arithmetic import MIN  # noqa
from polars_ta.tdx.arithmetic import MOD  # noqa
from polars_ta.tdx.arithmetic import POW  # noqa
from polars_ta.tdx.arithmetic import REVERSE  # noqa
from polars_ta.tdx.arithmetic import ROUND  # noqa
from polars_ta.tdx.arithmetic import ROUND2  # noqa
from polars_ta.tdx.arithmetic import SGN  # noqa
from polars_ta.tdx.arithmetic import SIGN  # noqa
from polars_ta.tdx.arithmetic import SIN  # noqa
from polars_ta.tdx.arithmetic import SQRT  # noqa
from polars_ta.tdx.arithmetic import SUB  # noqa
from polars_ta.tdx.arithmetic import TAN  # noqa
from polars_ta.tdx.choice import IF  # noqa
from polars_ta.tdx.choice import IFF  # noqa
from polars_ta.tdx.choice import IFN  # noqa
from polars_ta.tdx.choice import VALUEWHEN as ts_VALUEWHEN  # noqa
from polars_ta.tdx.energy import BRAR_AR as ts_BRAR_AR  # noqa
from polars_ta.tdx.energy import BRAR_BR as ts_BRAR_BR  # noqa
from polars_ta.tdx.energy import CR as ts_CR  # noqa
from polars_ta.tdx.energy import MASS as ts_MASS  # noqa
from polars_ta.tdx.energy import PSY as ts_PSY  # noqa
from polars_ta.tdx.logical import ALL as ts_ALL  # noqa
from polars_ta.tdx.logical import ANY as ts_ANY  # noqa
from polars_ta.tdx.logical import CROSS as ts_CROSS  # noqa
from polars_ta.tdx.logical import DOWNNDAY as ts_DOWNNDAY  # noqa
from polars_ta.tdx.logical import EVERY as ts_EVERY  # noqa
from polars_ta.tdx.logical import EXIST as ts_EXIST  # noqa
from polars_ta.tdx.logical import EXISTR as ts_EXISTR  # noqa
from polars_ta.tdx.logical import LAST as ts_LAST  # noqa
from polars_ta.tdx.logical import LONGCROSS as ts_LONGCROSS  # noqa
from polars_ta.tdx.logical import NDAY as ts_NDAY  # noqa
from polars_ta.tdx.logical import NOT  # noqa
from polars_ta.tdx.logical import UPNDAY as ts_UPNDAY  # noqa
from polars_ta.tdx.moving_average import BBI as ts_BBI  # noqa
from polars_ta.tdx.over_bought_over_sold import ATR as ts_ATR  # noqa
from polars_ta.tdx.over_bought_over_sold import BIAS as ts_BIAS  # noqa
from polars_ta.tdx.over_bought_over_sold import CCI as ts_CCI  # noqa
from polars_ta.tdx.over_bought_over_sold import KDJ as ts_KDJ  # noqa
from polars_ta.tdx.over_bought_over_sold import MFI as ts_MFI  # noqa
from polars_ta.tdx.over_bought_over_sold import MTM as ts_MTM  # noqa
from polars_ta.tdx.over_bought_over_sold import RSI as ts_RSI  # noqa
from polars_ta.tdx.over_bought_over_sold import RSV as ts_RSV  # noqa
from polars_ta.tdx.pattern import ts_WINNER_COST  # noqa
from polars_ta.tdx.pattern_feature import 仙人指路 as ts_仙人指路  # noqa
from polars_ta.tdx.pattern_feature import 低开大阳线 as ts_低开大阳线  # noqa
from polars_ta.tdx.pattern_feature import 低点搜寻 as ts_低点搜寻  # noqa
from polars_ta.tdx.pattern_feature import 出水芙蓉 as ts_出水芙蓉  # noqa
from polars_ta.tdx.pattern_feature import 出水芙蓉II as ts_出水芙蓉II  # noqa
from polars_ta.tdx.pattern_feature import 剑 as ts_剑  # noqa
from polars_ta.tdx.pattern_feature import 单阳不破选股 as ts_单阳不破选股  # noqa
from polars_ta.tdx.pattern_feature import 四串阳 as ts_四串阳  # noqa
from polars_ta.tdx.pattern_feature import 四串阴 as ts_四串阴  # noqa
from polars_ta.tdx.pattern_feature import 回补跳空向上缺口 as ts_回补跳空向上缺口  # noqa
from polars_ta.tdx.pattern_feature import 均线多头排列 as ts_均线多头排列  # noqa
from polars_ta.tdx.pattern_feature import 均线空头排列 as ts_均线空头排列  # noqa
from polars_ta.tdx.pattern_feature import 天量法则 as ts_天量法则  # noqa
from polars_ta.tdx.pattern_feature import 强势整理 as ts_强势整理  # noqa
from polars_ta.tdx.pattern_feature import 揉搓线 as ts_揉搓线  # noqa
from polars_ta.tdx.pattern_feature import 早晨之星 as ts_早晨之星  # noqa
from polars_ta.tdx.pattern_feature import 旭日初升 as ts_旭日初升  # noqa
from polars_ta.tdx.pattern_feature import 突破 as ts_突破  # noqa
from polars_ta.tdx.pattern_feature import 老鸭头 as ts_老鸭头  # noqa
from polars_ta.tdx.pattern_feature import 蜻蜓点水 as ts_蜻蜓点水  # noqa
from polars_ta.tdx.pattern_feature import 跳空缺口选股 as ts_跳空缺口选股  # noqa
from polars_ta.tdx.pattern_feature import 近日创历史新低 as ts_近日创历史新低  # noqa
from polars_ta.tdx.pattern_feature import 近日创历史新高 as ts_近日创历史新高  # noqa
from polars_ta.tdx.pattern_feature import 高开大阴线 as ts_高开大阴线  # noqa
from polars_ta.tdx.pattern_feature import 鸳鸯底 as ts_鸳鸯底  # noqa
from polars_ta.tdx.pressure_support import BOLL as ts_BOLL  # noqa
from polars_ta.tdx.pressure_support import BOLL_M as ts_BOLL_M  # noqa
from polars_ta.tdx.reference import BARSLAST as ts_BARSLAST  # noqa
from polars_ta.tdx.reference import BARSLASTCOUNT as ts_BARSLASTCOUNT  # noqa
from polars_ta.tdx.reference import BARSSINCE as ts_BARSSINCE  # noqa
from polars_ta.tdx.reference import BARSSINCEN as ts_BARSSINCEN  # noqa
from polars_ta.tdx.reference import COUNT as ts_COUNT  # noqa
from polars_ta.tdx.reference import CUMSUM as ts_CUMSUM  # noqa
from polars_ta.tdx.reference import DIFF as ts_DIFF  # noqa
from polars_ta.tdx.reference import DMA as ts_DMA  # noqa
from polars_ta.tdx.reference import EMA as ts_EMA  # noqa
from polars_ta.tdx.reference import EXPMA as ts_EXPMA  # noqa
from polars_ta.tdx.reference import EXPMEMA as ts_EXPMEMA  # noqa
from polars_ta.tdx.reference import FILTER as ts_FILTER  # noqa
from polars_ta.tdx.reference import HHV as ts_HHV  # noqa
from polars_ta.tdx.reference import HHVBARS as ts_HHVBARS  # noqa
from polars_ta.tdx.reference import HOD as ts_HOD  # noqa
from polars_ta.tdx.reference import LLV as ts_LLV  # noqa
from polars_ta.tdx.reference import LLVBARS as ts_LLVBARS  # noqa
from polars_ta.tdx.reference import LOD as ts_LOD  # noqa
from polars_ta.tdx.reference import LOWRANGE  # noqa
from polars_ta.tdx.reference import MA as ts_MA  # noqa
from polars_ta.tdx.reference import MAX  # noqa
from polars_ta.tdx.reference import MEMA as ts_MEMA  # noqa
from polars_ta.tdx.reference import MIN  # noqa
from polars_ta.tdx.reference import MULAR as ts_MULAR  # noqa
from polars_ta.tdx.reference import RANGE  # noqa
from polars_ta.tdx.reference import REF as ts_REF  # noqa
from polars_ta.tdx.reference import REFX as ts_REFX  # noqa
from polars_ta.tdx.reference import SMA_CN as ts_SMA_CN  # noqa
from polars_ta.tdx.reference import SUM as ts_SUM  # noqa
from polars_ta.tdx.reference import SUMIF as ts_SUMIF  # noqa
from polars_ta.tdx.reference import TMA as ts_TMA  # noqa
from polars_ta.tdx.reference import TR as ts_TR  # noqa
from polars_ta.tdx.reference import WMA as ts_WMA  # noqa
from polars_ta.tdx.statistic import AVEDEV as ts_AVEDEV  # noqa
from polars_ta.tdx.statistic import COVAR as ts_COVAR  # noqa
from polars_ta.tdx.statistic import DEVSQ as ts_DEVSQ  # noqa
from polars_ta.tdx.statistic import RELATE as ts_RELATE  # noqa
from polars_ta.tdx.statistic import SLOPE as ts_SLOPE  # noqa
from polars_ta.tdx.statistic import STD as ts_STD  # noqa
from polars_ta.tdx.statistic import STDDEV as ts_STDDEV  # noqa
from polars_ta.tdx.statistic import STDP as ts_STDP  # noqa
from polars_ta.tdx.statistic import VAR as ts_VAR  # noqa
from polars_ta.tdx.statistic import VARP as ts_VARP  # noqa
from polars_ta.tdx.statistic import ts_up_stat  # noqa
from polars_ta.tdx.trend import ADX as ts_ADX  # noqa
from polars_ta.tdx.trend import ADXR as ts_ADXR  # noqa
from polars_ta.tdx.trend import DPO as ts_DPO  # noqa
from polars_ta.tdx.trend import EMV as ts_EMV  # noqa
from polars_ta.tdx.trend import MINUS_DI as ts_MINUS_DI  # noqa
from polars_ta.tdx.trend import MINUS_DM as ts_MINUS_DM  # noqa
from polars_ta.tdx.trend import PLUS_DI as ts_PLUS_DI  # noqa
from polars_ta.tdx.trend import PLUS_DM as ts_PLUS_DM  # noqa
from polars_ta.tdx.trend_feature import N天内出现以涨停收盘 as ts_N天内出现以涨停收盘  # noqa
from polars_ta.tdx.trend_feature import N天内出现涨停 as ts_N天内出现涨停  # noqa
from polars_ta.tdx.trend_feature import N天内有跳空向上缺口 as ts_N天内有跳空向上缺口  # noqa
from polars_ta.tdx.trend_feature import N天内经常涨停 as ts_N天内经常涨停  # noqa
from polars_ta.tdx.trend_feature import N日内上涨多于下跌 as ts_N日内上涨多于下跌  # noqa
from polars_ta.tdx.trend_feature import N日内下跌多于上涨 as ts_N日内下跌多于上涨  # noqa
from polars_ta.tdx.trend_feature import N日内创新低 as ts_N日内创新低  # noqa
from polars_ta.tdx.trend_feature import N日内创新高 as ts_N日内创新高  # noqa
from polars_ta.tdx.trend_feature import N日内阳线多于阴线 as ts_N日内阳线多于阴线  # noqa
from polars_ta.tdx.trend_feature import N日内阴线多于阳线 as ts_N日内阴线多于阳线  # noqa
from polars_ta.tdx.trend_feature import 下跌多日再放量上涨 as ts_下跌多日再放量上涨  # noqa
from polars_ta.tdx.trend_feature import 价量渐低后阳包阴 as ts_价量渐低后阳包阴  # noqa
from polars_ta.tdx.trend_feature import 单日放量 as ts_单日放量  # noqa
from polars_ta.tdx.trend_feature import 小步碎阳 as ts_小步碎阳  # noqa
from polars_ta.tdx.trend_feature import 平台整理 as ts_平台整理  # noqa
from polars_ta.tdx.trend_feature import 拉升后多日调整 as ts_拉升后多日调整  # noqa
from polars_ta.tdx.trend_feature import 持续放量 as ts_持续放量  # noqa
from polars_ta.tdx.trend_feature import 持续缩量 as ts_持续缩量  # noqa
from polars_ta.tdx.trend_feature import 放量上攻 as ts_放量上攻  # noqa
from polars_ta.tdx.trend_feature import 昨日底部十字星 as ts_昨日底部十字星  # noqa
from polars_ta.tdx.trend_feature import 温和放量上攻 as ts_温和放量上攻  # noqa
from polars_ta.tdx.trend_feature import 突然放量 as ts_突然放量  # noqa
from polars_ta.tdx.trend_feature import 突破长期盘整 as ts_突破长期盘整  # noqa
from polars_ta.tdx.trend_feature import 跳空高开或低开 as ts_跳空高开或低开  # noqa
from polars_ta.tdx.trend_feature import 连续N天收阳线 as ts_连续N天收阳线  # noqa
from polars_ta.tdx.trend_feature import 连续N天收阴线 as ts_连续N天收阴线  # noqa
from polars_ta.tdx.trend_feature import 间隔放量 as ts_间隔放量  # noqa
from polars_ta.tdx.trend_feature import 阶段放量 as ts_阶段放量  # noqa
from polars_ta.tdx.trend_feature import 阶段缩量 as ts_阶段缩量  # noqa
from polars_ta.tdx.volume import OBV as ts_OBV  # noqa
from polars_ta.tdx.volume import VR as ts_VR  # noqa