# this code is auto generated by tools/prefix_vec.py

from polars_ta.wq.vector import vec_avg as cs_vec_avg  # noqa
from polars_ta.wq.vector import vec_choose as cs_vec_choose  # noqa
from polars_ta.wq.vector import vec_count as cs_vec_count  # noqa
from polars_ta.wq.vector import vec_ir as cs_vec_ir  # noqa
from polars_ta.wq.vector import vec_kurtosis as cs_vec_kurtosis  # noqa
from polars_ta.wq.vector import vec_l2_norm as cs_vec_l2_norm  # noqa
from polars_ta.wq.vector import vec_max as cs_vec_max  # noqa
from polars_ta.wq.vector import vec_min as cs_vec_min  # noqa
from polars_ta.wq.vector import vec_norm as cs_vec_norm  # noqa
from polars_ta.wq.vector import vec_percentage as cs_vec_percentage  # noqa
from polars_ta.wq.vector import vec_powersum as cs_vec_powersum  # noqa
from polars_ta.wq.vector import vec_range as cs_vec_range  # noqa
from polars_ta.wq.vector import vec_skewness as cs_vec_skewness  # noqa
from polars_ta.wq.vector import vec_stddev as cs_vec_stddev  # noqa
from polars_ta.wq.vector import vec_sum as cs_vec_sum  # noqa