import talib as _talib
from talib import abstract as _abstract


def _codegen_func(name, input_names, parameters, output_names):
    tpl = """
def {name}({aa}) -> pl.Expr:
    return {struct}({bb}).ta.{name}({cc})

"""

    extra_args = {'skip_nan': False, 'output_idx': None, 'schema': tuple(output_names), 'schema_format': "'{}'"}
    a1 = [f'{name}: pl.Expr' for name in input_names]
    a2 = [f'{k}: {type(v).__name__} = {v}' for k, v in parameters.items()]
    a3 = [f'{k}={v}' for k, v in extra_args.items()]
    aa = ', '.join(a1 + a2 + a3)

    bb = ', '.join(input_names)

    c1 = [f'{k}' for k, v in parameters.items()]
    c2 = [f'{k}={k}' for k, v in extra_args.items()]
    cc = ', '.join(c1 + c2)

    struct = 'pl.struct' if len(input_names) > 1 else ''
    return tpl.format(name=name, aa=aa,
                      struct=struct, bb=bb, cc=cc)


def codegen():
    head = """# generated by codegen_talib.py
import polars as pl

from polars_ta.utils.helper import TaLibHelper

_ = TaLibHelper

"""

    context = [head]
    for i, func_name in enumerate(_talib.get_functions()):
        """talib遍历"""
        info = _abstract.Function(func_name).info

        name = info['name']
        input_names = []
        for in_names in info['input_names'].values():
            if isinstance(in_names, (list, tuple)):
                input_names.extend(list(in_names))
            else:
                input_names.append(in_names)
        parameters = info['parameters']
        output_names = info['output_names']
        txt = _codegen_func(name, input_names, parameters, output_names)
        context.append(txt)

    return context


def save(context):
    import polars_ta.talib
    file = polars_ta.talib.__file__
    print('save to', file)
    with open(file, 'w', encoding='utf-8') as f:
        f.writelines(context)


if __name__ == '__main__':
    context = codegen()
    save(context)
