from tools.prefix import codegen_import_as, save

lines = ["""# this code is auto generated by tools/prefix_tdx.py
"""]
lines += codegen_import_as('polars_ta.tdx.arithmetic', include_modules=['polars_ta.wq.arithmetic'])
lines += codegen_import_as('polars_ta.tdx.choice', include_func=['VALUEWHEN'])
lines += codegen_import_as('polars_ta.tdx.energy', include_parameter=['N', 'N1'])
lines += codegen_import_as('polars_ta.tdx.logical', include_func=['CROSS', 'LONGCROSS', 'EXISTR', 'LAST'], include_parameter=['N'])
lines += codegen_import_as('polars_ta.tdx.moving_average', include_parameter=['M1'])
lines += codegen_import_as('polars_ta.tdx.over_bought_over_sold', include_modules=['polars_ta.ta.momentum'], include_parameter=['N', 'timeperiod'])
lines += codegen_import_as('polars_ta.tdx.pattern')
lines += codegen_import_as('polars_ta.tdx.pattern_feature', include_parameter=['N', 'M', 'N1'], include_func=['早晨之星', '剑', '天量法则', '四串阴', '四串阳', '出水芙蓉II', '高开大阴线', '低开大阳线', '跳空缺口选股', '老鸭头', '仙人指路'])
lines += codegen_import_as('polars_ta.tdx.pressure_support', include_parameter=['N'])
lines += codegen_import_as('polars_ta.tdx.reference', include_modules=['polars_ta.ta.overlap', 'polars_ta.ta.volatility', 'polars_ta.wq.arithmetic', 'polars_ta.wq.time_series'], include_func=['BARSLAST', 'BARSLASTCOUNT', 'BARSSINCE', 'DMA', 'CUMSUM', 'TR'], include_parameter=['N', 'd', 'timeperiod'])
lines += codegen_import_as('polars_ta.tdx.statistic', include_modules=['polars_ta.wq.time_series'], include_parameter=['timeperiod', 'd'])
lines += codegen_import_as('polars_ta.tdx.trend', include_parameter=['N'])
lines += codegen_import_as('polars_ta.tdx.trend_feature', include_parameter=['N', 'M', 'N1'], include_func=['下跌多日再放量上涨', '价量渐低后阳包阴', '单日放量', '跳空高开或低开'])
lines += codegen_import_as('polars_ta.tdx.volume', include_func=['OBV'], include_parameter=['N'])
save(lines, module='polars_ta.prefix.tdx', write=True)
